######################################
# Experiment configuration file for TractOracle-V2
# This file contains the configuration for the experiments
# to be run. This is used by submit_experiments.py to 
# generate SLURM-compatible scripts for running the experiments
# with different parameters.
# 
# Now, we also aim to support using this method locally.
# Everytime you wanna specify a path in the configuration below,
# you can use the following formats:
# 
# 1. If you have the same path for LOCAL and CLUSTER nodes:
#   some_dict:
#     location: "~/path/to/file/common/to/both"
#     ...
#   ...
# 
# 2. If you have different paths for LOCAL and CLUSTER nodes:
#   some_dict:
#     location:
#       local: "~/path/to/file/for/local"
#       cluster: "~/path/to/file/for/cluster"
#     ...
#   ...
# 
# Depending on the node you are building the script for, only
# the corresponding path will be used in the bash script generated.

######################################
## Data configuration
## Bunch of paths pointing to where the data is stored
## or where it should be stored.
######################################  
data: 
  SOURCEDIR:
    local: "~/Documents/FineTrack"
    cluster: "~/FineTrack"
  DATADIR:
    local: "~/Documents/FineTrack/data/datasets"
    cluster: "$SLURM_TMPDIR/data"
  EXPDIR:
    local: "~/Documents/FineTrack/data/experiments"
    cluster: "/home/levj1404/scratch/FineTrack-RLHF"
  LOGSDIR:
    local: "~/Documents/FineTrack/data/logs"
    cluster: "$SLURM_TMPDIR/logs"
  PROJECTS_DIR:
    local:
    cluster: "~/projects/def-pmjodoin/levje"

  ismrm2015:
    name: "ismrm2015"
    location:
      local: "~/Documents/FineTrack/data/datasets/ismrm2015_2mm/ismrm2015.hdf5"
      cluster: "~/projects/def-pmjodoin/levje/datasets/ismrm2015_2mm_ttl.tar.gz"
    tractometer_reference:
      local: "~/Documents/FineTrack/data/datasets/ismrm2015_2mm/scoring_data/t1.nii.gz" # Path within the dataset directory
      cluster: "scoring_data/t1.nii.gz"
    scoring_data:
      local: "~/Documents/FineTrack/data/datasets/ismrm2015_2mm/scoring_data/" # Path within the dataset directory
      cluster: "scoring_data/"
  tractoinferno: 
    name: "tractoinferno"
    location:
      local: "~/Documents/FineTrack/data/datasets/TractoInferno/tractoinferno_single.hdf5"
      cluster: "~/projects/rrg-descotea/levje/datasets/tractoinferno/tractoinferno_fa.hdf5"
  hcp: 
    name: "hcp"
    location:
      local: "~/Documents/FineTrack/data/datasets/TractoInferno/tractoinferno_single.hdf5" # TODO: Wrong
      cluster: "~/projects/rrg-descotea/levje/datasets/hcp_full_100/hcp_full_100_fa.hdf5"

######################################
## Global configuration
## These configurations are shared across all experiments
## These parameters can be overridden by the experiment
## configurations below.
######################################  
global:
  project_name: "SAC-InVivo-RLHF"
  reward_ckpt:
    local: "custom_models/ismrm_oracles_nb_points/OracleNet-Transformer-Crit-32-Classif/_best_vc_epoch.ckpt"
    cluster: "~/projects/def-pmjodoin/levje/oracles/ismrm_oracles_nb_points/OracleNet-Transformer-Crit-32-Classif/_best_vc_epoch.ckpt"
  crit_ckpt:
    local: "~/Documents/FineTrack/custom_models/ismrm_oracles_nb_points/OracleNet-Transformer-Crit-32-Dense/_best_vc_epoch.ckpt"
    cluster: "~/projects/def-pmjodoin/levje/oracles/ismrm_oracles_nb_points/OracleNet-Transformer-Crit-32-Dense/_best_vc_epoch.ckpt"
  launch_script: "FineTrack/trainers/sac_auto_train.py"
  use_comet: True
  hidden_dims: "1024-1024-1024"
  npv: 2
  min_length: 20
  max_length: 200
  noise: 0.0
  replay_size: 1000000
  binary_stopping_threshold: 0.1
  theta: 30
  n_dirs: 100
  gamma: 0.95
  n_actors: 4096
  batch_size: 4096
  seed: 1111
  utd: 1
  oracle_bonus: 10
  
  # Neighborhood
  neighborhood_type: "axes"
  neighborhood_radius: 1
  flatten_state: True
  fodf_encoder_ckpt: null
  conv_state: False

  # Misc
  log_interval: 50
  workspace: "ext-med-ia"
  time: "2-00:00:00"
  mem: "70000M"

# Extra configuration parameters
# These parameters can be added to an experiment configuration
# identifying its category in the extras-type field.
# End the name by _ to avoid putting this parameter when its null.
extras:
  rlhf:
    pretrain_max_ep: 0
    warmup_agent_steps: 150
    agent_train_steps: 50
    first_oracle_train_steps: 5
    oracle_train_steps: 1
    oracle_lr: 0.0005
    dataset_to_augment_: null
    nb_new_streamlines_per_iter: 250000
    alg: "SACAuto"
    rbx_validator: True
    rlhf_inter_npv: 2
    oracle_batch_size: 1024
    num_workers: 4

    atlas_directory:
      local: "/home/local/USHERBROOKE/levj1404/Documents/rbx_flow/atlas"
      cluster: "/home/levj1404/rbx_binary/rbx_flow/atlas"
  other:



######################################
## Experiment configurations
## 
## You can add extra configuration parameters
## to the experiment configurations by adding
## extras-type: "rlhf"
######################################  

experiments:
  - exp_name: "RLHF-Inferno-SAC-3K"
    dataset: "tractoinferno"
    lr: 0.0005
    max_ep: 3000
    launch_script: "FineTrack/trainers/rlhf_train_simple.py"
    reward_ckpt:
      local: "/home/local/USHERBROOKE/levj1404/Documents/FineTrack/custom_models/tractoinferno_full_oracle/inferno_rbx_128pts_epoch4.ckpt"
      cluster: "~/projects/rrg-descotea/levje/oracles/tractoinferno_rbx/inferno_rbx_128pts_epoch4.ckpt"
    crit_ckpt:
      local: "/home/local/USHERBROOKE/levj1404/Documents/FineTrack/custom_models/tractoinferno_full_oracle/inferno_rbx_128pts_epoch4.ckpt"
      cluster: "~/projects/rrg-descotea/levje/oracles/tractoinferno_rbx/inferno_rbx_128pts_epoch4.ckpt"
    time: "0-47:00:00"
    project_name: "finetrack-tractoinferno-rlhf"
    extra_type: "rlhf"
    alg: "SACAuto"

  - exp_name: "RLHF-Inferno-CrossQ-3K"
    dataset: "tractoinferno"
    lr: 0.0005
    max_ep: 3000
    launch_script: "FineTrack/trainers/rlhf_train_simple.py"
    reward_ckpt:
      local: "/home/local/USHERBROOKE/levj1404/Documents/FineTrack/custom_models/tractoinferno_full_oracle/inferno_rbx_128pts_epoch4.ckpt"
      cluster: "~/projects/rrg-descotea/levje/oracles/tractoinferno_rbx/inferno_rbx_128pts_epoch4.ckpt"
    crit_ckpt:
      local: "/home/local/USHERBROOKE/levj1404/Documents/FineTrack/custom_models/tractoinferno_full_oracle/inferno_rbx_128pts_epoch4.ckpt"
      cluster: "~/projects/rrg-descotea/levje/oracles/tractoinferno_rbx/inferno_rbx_128pts_epoch4.ckpt"
    time: "0-47:00:00"
    project_name: "finetrack-tractoinferno-rlhf"
    extra_type: "rlhf"

  - exp_name: "RLHF-HCP-CrossQ-3K"
    dataset: "hcp"
    lr: 0.0005
    max_ep: 3000
    launch_script: "FineTrack/trainers/rlhf_train_simple.py"
    reward_ckpt:
      local: "/home/local/USHERBROOKE/levj1404/Documents/FineTrack/custom_models/tractoinferno_full_oracle/inferno_rbx_128pts_epoch4.ckpt" # TODO: Wrong
      cluster: "~/projects/rrg-descotea/levje/oracles/hcp_rbx/hcp_rbx_32pts_epoch14.ckpt" # INFERNO ORACLE
    crit_ckpt:
      local: "/home/local/USHERBROOKE/levj1404/Documents/FineTrack/custom_models/tractoinferno_full_oracle/inferno_rbx_128pts_epoch4.ckpt" # TODO: Wrong
      cluster: "~/projects/rrg-descotea/levje/oracles/hcp_rbx/hcp_rbx_32pts_epoch14.ckpt" # INFERNO ORACLE
    time: "0-47:00:00"
    project_name: "finetrack-hcp-rlhf"
    extra_type: "rlhf"
    alg: "CrossQ"

  - exp_name: "RLHF-HCP-SAC-3K"
    dataset: "hcp"
    lr: 0.0005
    max_ep: 3000
    launch_script: "FineTrack/trainers/rlhf_train_simple.py"
    reward_ckpt:
      local: "/home/local/USHERBROOKE/levj1404/Documents/FineTrack/custom_models/tractoinferno_full_oracle/inferno_rbx_128pts_epoch4.ckpt" # TODO: Wrong
      cluster: "~/projects/rrg-descotea/levje/oracles/hcp_rbx/hcp_rbx_32pts_epoch14.ckpt" # INFERNO ORACLE
    crit_ckpt:
      local: "/home/local/USHERBROOKE/levj1404/Documents/FineTrack/custom_models/tractoinferno_full_oracle/inferno_rbx_128pts_epoch4.ckpt" # TODO: Wrong
      cluster: "~/projects/rrg-descotea/levje/oracles/hcp_rbx/hcp_rbx_32pts_epoch14.ckpt" # INFERNO ORACLE
    time: "0-47:00:00"
    project_name: "finetrack-hcp-rlhf"
    extra_type: "rlhf"
    alg: "SACAuto"
