######################################
# Experiment configuration file for TractOracle-V2
# This file contains the configuration for the experiments
# to be run. This is used by submit_experiments.py to
# generate SLURM-compatible scripts for running the experiments
# with different parameters.
#
# Now, we also aim to support using this method locally.
# Everytime you wanna specify a path in the configuration below,
# you can use the following formats:
#
# 1. If you have the same path for LOCAL and CLUSTER nodes:
#   some_dict:
#     location: "~/path/to/file/common/to/both"
#     ...
#   ...
#
# 2. If you have different paths for LOCAL and CLUSTER nodes:
#   some_dict:
#     location:
#       local: "~/path/to/file/for/local"
#       cluster: "~/path/to/file/for/cluster"
#     ...
#   ...
#
# Depending on the node you are building the script for, only
# the corresponding path will be used in the bash script generated.

######################################
## Data configuration
## Bunch of paths pointing to where the data is stored
## or where it should be stored.
######################################
data:
  SOURCEDIR:
    local: "~/Documents/FineTrack"
    cluster: "~/FineTrack"
  DATADIR:
    local: "~/Documents/FineTrack/data/datasets"
    cluster: "$SLURM_TMPDIR/data"
  EXPDIR:
    local: "~/Documents/FineTrack/data/experiments"
    cluster: "/home/levj1404/scratch/FineTrack-IRT-Even-More"
  LOGSDIR:
    local: "~/Documents/FineTrack/data/logs"
    cluster: "$SLURM_TMPDIR/logs"
  PROJECTS_DIR:
    local:
    cluster: "~/projects/def-pmjodoin/levje"

  tractoinferno:
    name: "tractoinferno"
    location: "~/projects/def-pmjodoin/levje/datasets/tractoinferno/tractoinferno_fa.hdf5"
  hcp:
    name: "hcp"
    location: "~/projects/def-pmjodoin/levje/datasets/hcp_full_100/hcp_full_100_fa.hdf5"

######################################
## Global configuration
## These configurations are shared across all experiments
## These parameters can be overridden by the experiment
## configurations below.
######################################
global:
  project_name: "FineTrack-IRT-Even-More"
  launch_script: "FineTrack/trainers/rlhf_train_simple.py"
  use_comet: True
  hidden_dims: "1024-1024-1024"
  npv: 2
  min_length: 20
  max_length: 200
  noise: 0.0
  replay_size: 1000000
  binary_stopping_threshold: 0.1
  theta: 30
  n_dirs: 100
  gamma: 0.95
  n_actors: 4096
  batch_size: 4096
  utd: 1
  lr: 0.0005
  max_ep: 30
  dataset: "hcp"

  # Oracle
  oracle_bonus: 10
  oracle_validator: True
  oracle_stopping_criterion: True
  reward_ckpt:
    local: "/home/local/USHERBROOKE/levj1404/Documents/FineTrack/custom_models/tractoinferno_full_oracle/inferno_rbx_128pts_epoch4.ckpt"
    cluster: "/home/levj1404/projects/rrg-descotea/levje/oracles/hcp/rbx_based/hcp_rbx_32pts_epoch14.ckpt"
  crit_ckpt:
    local: "/home/local/USHERBROOKE/levj1404/Documents/FineTrack/custom_models/tractoinferno_full_oracle/inferno_rbx_128pts_epoch4.ckpt"
    cluster: "/home/levj1404/projects/rrg-descotea/levje/oracles/hcp/rbx_based/hcp_rbx_32pts_epoch14.ckpt"

  # Neighborhood
  neighborhood_type: "axes"
  neighborhood_radius: 1
  flatten_state: True
  fodf_encoder_ckpt: null
  conv_state: False

  # Misc
  log_interval: 50
  workspace: "ext-med-ia"
  cpus: 2
  time: "5-00:00:00"
  mem: "60000M"
  seeds: [1111]

# Extra configuration parameters
# These parameters can be added to an experiment configuration
# identifying its category in the extras-type field.
# End the name by _ to avoid putting this parameter when its null.
extras:
  rlhf:
    pretrain_max_ep_: 0
    warmup_agent_steps: 150
    agent_train_steps: 100
    first_oracle_train_steps: 5
    oracle_train_steps: 3
    oracle_lr: 0.0005
    dataset_to_augment_: null
    nb_new_streamlines_per_iter: 500000
    alg: "SACAuto"
    rlhf_inter_npv: 2
    oracle_batch_size: 1024
    num_workers: 4

  rbx:
    rbx_validator: True
    rbx_pipeline:
      local: "/home/local/USHERBROOKE/levj1404/Documents/rbx_flow/main.nf"
      cluster: "/home/levj1404/rbx_binary/rbx_flow/main.nf"

    atlas_directory:
      local: "/home/local/USHERBROOKE/levj1404/Documents/rbx_flow/atlas"
      cluster: "/home/levj1404/rbx_binary/rbx_flow/atlas"

  extractor:
    extractor_validator: True
    extractor_target:
      local: ~/Documents/FineTrack/data/mni_template/JHU_MNI_SS_T1_brain_182x218x182_conv_f.nii.gz
      cluster: ~/extractor_flow/templates/JHU_MNI_SS_T1_brain_182x218x182_conv_f.nii.gz

######################################
## Experiment configurations
##
## You can add extra configuration parameters
## to the experiment configurations by adding
## extras-type: "rlhf"
######################################

experiments:
# This experiment configuration is built for CEDAR on Jun 13, 2025.

# RBX-based experiments
  - exp_name: "HCP-SAC-IRT-RBX"
    alg: "SACAuto"
    extra_type: ["rlhf", "rbx"]
    cpus: 8
    mem: "80G"
    pretrain_max_ep_: null
    agent_checkpoint: "/home/levj1404/projects/def-pmjodoin/levje/checkpoints/hcp/SAC-3K/1111/last_model_state.ckpt"
    reward_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/hcp/rbx_based/hcp_rbx_32pts_epoch14.ckpt"
    crit_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/hcp/rbx_based/hcp_rbx_32pts_epoch14_copy.ckpt"

  - exp_name: "HCP-CrossQ-IRT-RBX"
    alg: "CrossQ"
    extra_type: ["rlhf", "rbx"]
    cpus: 8
    mem: "80G"
    pretrain_max_ep_: null
    agent_checkpoint: "/home/levj1404/projects/def-pmjodoin/levje/checkpoints/hcp/CrossQ-3K/2222/last_model_state.ckpt"
    reward_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/hcp/rbx_based/hcp_rbx_32pts_epoch14.ckpt"
    crit_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/hcp/rbx_based/hcp_rbx_32pts_epoch14_copy.ckpt"

  - exp_name: "INF-SAC-IRT-RBX"
    alg: "SACAuto"
    extra_type: ["rlhf", "rbx"]
    cpus: 8
    mem: "80G"
    pretrain_max_ep_: null
    agent_checkpoint: "/home/levj1404/projects/def-pmjodoin/levje/checkpoints/inferno/SAC-3K/2222/last_model_state.ckpt"
    reward_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/tractoinferno/rbx_based/inferno_rbx_32pts.ckpt"
    crit_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/tractoinferno/rbx_based/inferno_rbx_32pts_copy.ckpt"

  - exp_name: "INF-CrossQ-IRT-RBX"
    alg: "CrossQ"
    extra_type: ["rlhf", "rbx"]
    cpus: 8
    mem: "80G"
    pretrain_max_ep_: null
    agent_checkpoint: "/home/levj1404/projects/def-pmjodoin/levje/checkpoints/inferno/CrossQ-3K/2222/last_model_state.ckpt"
    reward_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/tractoinferno/rbx_based/inferno_rbx_32pts.ckpt"
    crit_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/tractoinferno/rbx_based/inferno_rbx_32pts_copy.ckpt"

# Extractors-based experiments
  - exp_name: "HCP-SAC-IRT-EXT"
    alg: "SACAuto"
    extra_type: ["rlhf", "extractor"]
    cpus: 8
    mem: "80G"
    pretrain_max_ep_: null
    agent_checkpoint: "/home/levj1404/scratch/FineTrack-All-Seeds/HCP-SAC-3K/HCP-SAC-3K_1111_2025-06-04_13-49-05/1111/model/last_model_state.ckpt"
    reward_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/hcp/extractor_based/hcp_32pts_epoch74.ckpt"
    crit_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/hcp/extractor_based/hcp_32pts_epoch74_copy.ckpt"

  - exp_name: "HCP-CrossQ-IRT-EXT"
    alg: "CrossQ"
    extra_type: ["rlhf", "extractor"]
    cpus: 8
    mem: "80G"
    pretrain_max_ep_: null
    agent_checkpoint: "/home/levj1404/scratch/FineTrack-All-Seeds/HCP-CrossQ-3K/HCP-CrossQ-3K_1111_2025-06-04_13-49-05/1111/model/last_model_state.ckpt"
    reward_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/hcp/extractor_based/hcp_32pts_epoch74.ckpt"
    crit_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/hcp/extractor_based/hcp_32pts_epoch74_copy.ckpt"

  - exp_name: "INF-SAC-IRT-EXT"
    alg: "SACAuto"
    extra_type: ["rlhf", "extractor"]
    cpus: 8
    mem: "80G"
    pretrain_max_ep_: null
    agent_checkpoint: "/home/levj1404/scratch/FineTrack-All-Seeds/Inferno-SAC-3K/Inferno-SAC-3K_1111_2025-06-04_13-49-05/1111/model/last_model_state.ckpt"
    reward_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/tractoinferno/extractor_based/tractoinferno_32pts_epoch74.ckpt"
    crit_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/tractoinferno/extractor_based/tractoinferno_32pts_epoch74_copy.ckpt"

  - exp_name: "INF-CrossQ-IRT-EXT"
    alg: "CrossQ"
    extra_type: ["rlhf", "extractor"]
    cpus: 8
    mem: "80G"
    pretrain_max_ep_: null
    agent_checkpoint: "/home/levj1404/scratch/FineTrack-All-Seeds/Inferno-CrossQ-3K/Inferno-CrossQ-3K_1111_2025-06-04_13-49-05/1111/model/last_model_state.ckpt"
    reward_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/tractoinferno/extractor_based/tractoinferno_32pts_epoch74.ckpt"
    crit_ckpt: "/home/levj1404/projects/def-pmjodoin/levje/oracles/tractoinferno/extractor_based/tractoinferno_32pts_epoch74_copy.ckpt"